const sb=supabase.createClient('https://smijqljrxhafvizonqui.supabase.co','sb_publishable_RLdYeKWJz2HixpCThdqVTg_TtSmH4H9');
const SLUG='taehyung-chaeyeon',BUCKET='wedding-images',PUBLIC='https://duringbbi.github.io/Wedding/';
let w=null,u=null,owner=false,items=[],rsvpItems=[],guestItems=[],dragId=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const val=id=>$(id).value.trim();const nullVal=id=>val(id)||null;
async function loadWedding(){const r=await sb.from('wedding').select('*').eq('slug',SLUG).single();if(r.error)throw r.error;w=r.data}
function setInput(id,v){$(id).value=v||''}
function fill(){setInput('groom',w.groom_name);setInput('bride',w.bride_name);setInput('date',w.wedding_date);setInput('time',String(w.wedding_time||'').slice(0,5));setInput('venue',w.venue_name);setInput('venueAddress',w.venue_address);setInput('venuePhone',w.venue_phone);setInput('greeting',w.greeting);setInput('groomPhone',w.groom_phone);setInput('bridePhone',w.bride_phone);setInput('groomFatherName',w.groom_father_name);setInput('groomFatherPhone',w.groom_father_phone);setInput('groomMotherName',w.groom_mother_name);setInput('groomMotherPhone',w.groom_mother_phone);setInput('brideFatherName',w.bride_father_name);setInput('brideFatherPhone',w.bride_father_phone);setInput('brideMotherName',w.bride_mother_name);setInput('brideMotherPhone',w.bride_mother_phone);setInput('subwayInfo',w.subway_info);setInput('busInfo',w.bus_info);setInput('parkingInfo',w.parking_info);setInput('groomBank',w.groom_bank);setInput('groomAccountName',w.groom_account_name);setInput('groomAccount',w.groom_account);setInput('brideBank',w.bride_bank);setInput('brideAccountName',w.bride_account_name);setInput('brideAccount',w.bride_account);$('coverPreview').src=w.cover_image_url||'';$('useCover').checked=w.use_cover_as_share_image!==false;setInput('shareTitle',w.share_title);setInput('shareDesc',w.share_description);$('isPublished').checked=w.is_published!==false;updatePublishLabel();sharePreview();setLock()}
function updatePublishLabel(){$('publishLabel').textContent=$('isPublished').checked?'공개':'비공개'}$('isPublished').onchange=updatePublishLabel;
function sharePreview(){const same=$('useCover').checked;$('sharePreview').src=(same?w.cover_image_url:(w.share_image_url||w.cover_image_url))||'';$('shareFile').disabled=same;$('shareUpload').disabled=same||!owner}
function setLock(){owner=!!u&&u.id===w.admin_user_id;$('lock').classList.toggle('hidden',owner);document.querySelectorAll('button,input,textarea,select').forEach(el=>{if(el.closest('#login'))return;if(['logout'].includes(el.id))return;if(!owner)el.disabled=true});$('shareUpload').disabled=!owner||$('useCover').checked}
function ext(f){return({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[f.type]||'jpg')}
async function upload(f,folder){if(!owner)throw Error('관리자 권한이 필요합니다.');if(!f)throw Error('사진을 선택해 주세요.');if(f.size>50*1024*1024)throw Error('50MB 이하 이미지로 선택해 주세요.');const path=`${w.id}/${folder}/${Date.now()}-${crypto.randomUUID()}.${ext(f)}`,r=await sb.storage.from(BUCKET).upload(path,f,{contentType:f.type,cacheControl:'31536000'});if(r.error)throw r.error;return{path,url:sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}}
function refreshPreview(){$('previewFrame').src=PUBLIC+'?t='+Date.now()}
$('loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await sb.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});$('loginStatus').textContent=r.error?r.error.message:'';if(!r.error)init()};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('useCover').onchange=sharePreview;
$('save').onclick=async()=>{if(!owner)return;const p={groom_name:val('groom'),bride_name:val('bride'),wedding_date:val('date'),wedding_time:val('time'),venue_name:val('venue'),venue_address:nullVal('venueAddress'),venue_phone:nullVal('venuePhone'),greeting:val('greeting'),groom_phone:nullVal('groomPhone'),bride_phone:nullVal('bridePhone'),groom_father_name:nullVal('groomFatherName'),groom_father_phone:nullVal('groomFatherPhone'),groom_mother_name:nullVal('groomMotherName'),groom_mother_phone:nullVal('groomMotherPhone'),bride_father_name:nullVal('brideFatherName'),bride_father_phone:nullVal('brideFatherPhone'),bride_mother_name:nullVal('brideMotherName'),bride_mother_phone:nullVal('brideMotherPhone'),subway_info:nullVal('subwayInfo'),bus_info:nullVal('busInfo'),parking_info:nullVal('parkingInfo'),groom_bank:nullVal('groomBank'),groom_account_name:nullVal('groomAccountName'),groom_account:nullVal('groomAccount'),bride_bank:nullVal('brideBank'),bride_account_name:nullVal('brideAccountName'),bride_account:nullVal('brideAccount'),share_title:nullVal('shareTitle'),share_description:nullVal('shareDesc'),use_cover_as_share_image:$('useCover').checked,share_image_url:$('useCover').checked?w.cover_image_url:w.share_image_url,is_published:$('isPublished').checked,updated_at:new Date().toISOString()};const r=await sb.from('wedding').update(p).eq('id',w.id);if(r.error)return alert(r.error.message);Object.assign(w,p);alert('저장되었습니다.');refreshPreview()};
$('coverUpload').onclick=async()=>{try{$('coverStatus').textContent='업로드 중...';const x=await upload($('coverFile').files[0],'cover'),p={cover_image_url:x.url,cover_image_path:x.path,updated_at:new Date().toISOString()};if($('useCover').checked)p.share_image_url=x.url;const r=await sb.from('wedding').update(p).eq('id',w.id);if(r.error)throw r.error;Object.assign(w,p);$('coverPreview').src=x.url;sharePreview();$('coverStatus').textContent='업로드 완료';refreshPreview()}catch(e){$('coverStatus').textContent=e.message}};
$('shareUpload').onclick=async()=>{try{$('shareStatus').textContent='업로드 중...';const x=await upload($('shareFile').files[0],'share'),p={share_image_url:x.url,use_cover_as_share_image:false,updated_at:new Date().toISOString()},r=await sb.from('wedding').update(p).eq('id',w.id);if(r.error)throw r.error;Object.assign(w,p);$('useCover').checked=false;sharePreview();$('shareStatus').textContent='업로드 완료'}catch(e){$('shareStatus').textContent=e.message}};
async function loadGallery(){const r=await sb.from('wedding_gallery').select('*').eq('wedding_id',w.id).order('sort_order');if(r.error)throw r.error;items=r.data||[];renderGallery()}
function renderGallery(){$('galleryCount').textContent=items.length;$('gallery').innerHTML=items.map((x,i)=>`<div class="g" draggable="true" data-gid="${x.id}"><img src="${x.image_url}" loading="lazy" decoding="async"><button class="gDelete" data-del="${x.id}">×</button><div class="gControls"><button data-up="${x.id}" ${i===0?'disabled':''}>↑</button><button data-down="${x.id}" ${i===items.length-1?'disabled':''}>↓</button></div></div>`).join('');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>delGallery(b.dataset.del));document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>moveGallery(b.dataset.up,-1));document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>moveGallery(b.dataset.down,1));document.querySelectorAll('[data-gid]').forEach(el=>{el.ondragstart=()=>{dragId=el.dataset.gid;el.classList.add('dragging')};el.ondragend=()=>{dragId=null;el.classList.remove('dragging');document.querySelectorAll('.g').forEach(x=>x.classList.remove('dragover'))};el.ondragover=e=>{e.preventDefault();el.classList.add('dragover')};el.ondragleave=()=>el.classList.remove('dragover');el.ondrop=async e=>{e.preventDefault();el.classList.remove('dragover');if(!dragId||dragId===el.dataset.gid)return;const from=items.findIndex(x=>x.id===dragId),to=items.findIndex(x=>x.id===el.dataset.gid),[m]=items.splice(from,1);items.splice(to,0,m);renderGallery();await persistGalleryOrder()}})}
async function persistGalleryOrder(){if(!owner)return;$('galleryStatus').textContent='순서 저장 중...';const rs=await Promise.all(items.map((x,i)=>sb.from('wedding_gallery').update({sort_order:i}).eq('id',x.id)));const err=rs.find(x=>x.error)?.error;if(err){$('galleryStatus').textContent=err.message;await loadGallery();return}$('galleryStatus').textContent='순서 저장 완료';refreshPreview()}
async function moveGallery(id,d){const i=items.findIndex(x=>x.id===id),j=i+d;if(i<0||j<0||j>=items.length)return;[items[i],items[j]]=[items[j],items[i]];renderGallery();await persistGalleryOrder()}
$('galleryUpload').onclick=async()=>{const fs=[...$('galleryFiles').files];if(!fs.length)return $('galleryStatus').textContent='사진을 선택해 주세요.';try{let n=items.length?Math.max(...items.map(x=>x.sort_order||0))+1:0;for(let i=0;i<fs.length;i++){$('galleryStatus').textContent=`${i+1}/${fs.length} 업로드 중...`;const x=await upload(fs[i],'gallery'),r=await sb.from('wedding_gallery').insert({wedding_id:w.id,image_url:x.url,storage_path:x.path,sort_order:n++});if(r.error)throw r.error}await loadGallery();$('galleryFiles').value='';$('galleryStatus').textContent='업로드 완료';refreshPreview()}catch(e){$('galleryStatus').textContent=e.message}};
async function delGallery(id){if(!owner||!confirm('이 사진을 삭제할까요?'))return;const x=items.find(v=>v.id===id),r=await sb.from('wedding_gallery').delete().eq('id',id);if(r.error)return alert(r.error.message);if(x?.storage_path)await sb.storage.from(BUCKET).remove([x.storage_path]);await loadGallery();await persistGalleryOrder()}
const fmt=v=>{if(!v)return'';try{return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return''}};
async function loadRsvp(){if(!owner)return;const r=await sb.from('rsvp').select('id,name,side,attendance,guest_count,meal,message,created_at').eq('wedding_id',w.id).order('created_at',{ascending:false});if(r.error){$('rsvpAdminStatus').textContent=r.error.message;return}rsvpItems=r.data||[];$('rsvpAdminStatus').textContent=`마지막 갱신 ${new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`;renderRsvp()}
function renderRsvp(){const side=$('rsvpSideFilter').value,att=$('rsvpAttendanceFilter').value,rows=rsvpItems.filter(x=>(!side||x.side===side)&&(!att||x.attendance===att));$('statTotal').textContent=rsvpItems.length;$('statYes').textContent=rsvpItems.filter(x=>x.attendance==='참석').length;$('statNo').textContent=rsvpItems.filter(x=>x.attendance==='불참').length;$('statPeople').textContent=rsvpItems.filter(x=>x.attendance==='참석').reduce((n,x)=>n+Number(x.guest_count||0),0);$('rsvpSideStats').textContent=`신랑측 ${rsvpItems.filter(x=>x.side==='신랑측').length} · 신부측 ${rsvpItems.filter(x=>x.side==='신부측').length}`;$('rsvpList').innerHTML=rows.length?rows.map(x=>`<div class="item"><div class="itemHead"><div><div class="name">${esc(x.name)}</div><div class="badges"><span class="badge">${esc(x.side)}</span><span class="badge ${x.attendance==='참석'?'yes':'no'}">${esc(x.attendance)}</span>${x.attendance==='참석'?`<span class="badge">${Number(x.guest_count||1)}명</span>${x.meal?`<span class="badge">식사 ${esc(x.meal)}</span>`:''}`:''}</div></div><button class="btn danger" data-rsvp-del="${x.id}">삭제</button></div>${x.message?`<div class="msg">${esc(x.message)}</div>`:''}<div class="meta">${fmt(x.created_at)}</div></div>`).join(''):'<div class="empty">조건에 맞는 RSVP 응답이 없습니다.</div>';document.querySelectorAll('[data-rsvp-del]').forEach(b=>b.onclick=()=>deleteRsvp(b.dataset.rsvpDel))}
async function deleteRsvp(id){if(!owner||!confirm('이 RSVP 응답을 삭제할까요?'))return;const r=await sb.from('rsvp').delete().eq('id',id);if(r.error)return alert(r.error.message);await loadRsvp()}
$('rsvpRefresh').onclick=loadRsvp;$('rsvpSideFilter').onchange=renderRsvp;$('rsvpAttendanceFilter').onchange=renderRsvp;
$('rsvpCsv').onclick=()=>{if(!rsvpItems.length)return alert('다운로드할 RSVP 응답이 없습니다.');const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',rows=[['성함','구분','참석여부','인원','식사','전달사항','등록일'],...rsvpItems.map(x=>[x.name,x.side,x.attendance,x.guest_count,x.meal||'',x.message||'',fmt(x.created_at)])],csv='\uFEFF'+rows.map(r=>r.map(q).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`wedding-rsvp-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
async function loadGuestAdmin(){if(!owner)return;const r=await sb.from('guestbook').select('id,name,message,is_hidden,created_at').eq('wedding_id',w.id).order('created_at',{ascending:false});if(r.error){$('guestAdminStatus').textContent=r.error.message;return}guestItems=r.data||[];$('guestAdminStatus').textContent=`마지막 갱신 ${new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`;renderGuestAdmin()}
function renderGuestAdmin(){const f=$('guestFilter').value,rows=guestItems.filter(x=>!f||(f==='hidden'?x.is_hidden:!x.is_hidden));$('guestStats').textContent=`전체 ${guestItems.length} · 공개 ${guestItems.filter(x=>!x.is_hidden).length} · 숨김 ${guestItems.filter(x=>x.is_hidden).length}`;$('guestAdminList').innerHTML=rows.length?rows.map(x=>`<div class="item"><div class="itemHead"><div><div class="name">${esc(x.name)}</div><div class="badges">${x.is_hidden?'<span class="badge hiddenBadge">숨김</span>':'<span class="badge yes">공개</span>'}</div></div><div class="guestActions"><button class="btn ${x.is_hidden?'success':'ghost'}" data-guest-toggle="${x.id}">${x.is_hidden?'다시 공개':'숨기기'}</button><button class="btn danger" data-guest-del="${x.id}">삭제</button></div></div><div class="msg">${esc(x.message)}</div><div class="meta">${fmt(x.created_at)}</div></div>`).join(''):'<div class="empty">조건에 맞는 방명록이 없습니다.</div>';document.querySelectorAll('[data-guest-toggle]').forEach(b=>b.onclick=()=>toggleGuest(b.dataset.guestToggle));document.querySelectorAll('[data-guest-del]').forEach(b=>b.onclick=()=>deleteGuest(b.dataset.guestDel))}
async function toggleGuest(id){const x=guestItems.find(v=>v.id===id);if(!x)return;const r=await sb.from('guestbook').update({is_hidden:!x.is_hidden}).eq('id',id);if(r.error)return alert(r.error.message);await loadGuestAdmin();refreshPreview()}
async function deleteGuest(id){if(!confirm('이 방명록을 완전히 삭제할까요?'))return;const r=await sb.from('guestbook').delete().eq('id',id);if(r.error)return alert(r.error.message);await loadGuestAdmin();refreshPreview()}
$('guestRefresh').onclick=loadGuestAdmin;$('guestFilter').onchange=renderGuestAdmin;
async function init(){await loadWedding();u=(await sb.auth.getUser()).data.user;if(!u){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}$('login').classList.add('hidden');$('app').classList.remove('hidden');$('who').textContent=u.email+(u.id===w.admin_user_id?' · 관리자 인증 완료':'');fill();if(owner){await Promise.all([loadGallery(),loadRsvp(),loadGuestAdmin()])}}
init().catch(e=>$('loginStatus').textContent=e.message);